apiVersion: v1
kind: Service
metadata:
  name: dotnet-service
spec:
  selector:
    app: dotapplication
  type: LoadBalancer
  ports:
  - name: dotapplication
    protocol: TCP
    port: 80
    targetPort: 5000 
